/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConversationId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'encryptedContent' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'title' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConversation' : IDL.Func([IDL.Text], [ConversationId], []),
  'deleteConversation' : IDL.Func([ConversationId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([ConversationId], [Conversation], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateConversation' : IDL.Func(
      [ConversationId, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConversationId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'encryptedContent' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'title' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConversation' : IDL.Func([IDL.Text], [ConversationId], []),
    'deleteConversation' : IDL.Func([ConversationId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func([ConversationId], [Conversation], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateConversation' : IDL.Func(
        [ConversationId, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };